spring:
  application:
    name: postman-pechkin
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
server:
  port: 8081
logging:
  level:
    ru.ivamly.system.postmanpechkin: TRACE
